## Procedure for converting PIDNs to Yokoyama Lab IDs

In [3]:
import numpy as np
import pandas as pd
from numpy.random import default_rng

First, import CSV of PIDNs, extract PIDN values:

In [23]:
df = pd.read_csv (r'/Users/aoddi/Documents/Yokoyama Lab/ADWB/ID Conversion/Test PIDNs.csv')
PIDN_col = df.iloc[:,0]
PIDNs = PIDN_col.values
PIDNs

array([3309, 9215, 5143, 8407, 5299, 2056, 3127, 6968, 6369, 6755, 5374,
       3860, 8745, 8417, 8694, 1271, 9940, 2757, 4306, 2479, 4258, 8987,
       5116, 9704, 6747, 7173, 6183, 8914, 3237, 4358, 8664, 7477, 1419,
       3618, 1220, 7709, 9280, 6651, 8428, 5896, 5964, 4499, 2859, 2807,
       7197, 9723, 5753, 4381, 9568, 8275, 9538, 8688, 3119, 8492, 7354,
       5528, 1344, 8114, 4608, 8959, 3346, 1333, 8425, 9669, 1365, 8305,
       6637, 4707, 3022, 8531, 6338, 3977, 5295, 5087, 8620, 2177, 5317,
       5922, 8919, 7009, 2140, 2848, 4649, 5525, 3672, 8347, 3283, 1685,
       9059, 5293, 9240, 1226, 1100, 6263, 5627, 6969, 9482, 7764, 3094,
       2064])

Find number of samples, and select range for new Yokoyama IDs.

In [36]:
num_PIDNs = len(PIDNs)
start = 100
end = start + num_PIDNs
YOK_ID_range = np.arange(start, end)
YOK_ID_range

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

Shuffle array with range of possible IDs.

In [37]:
rng = np.random.default_rng()
rng.shuffle(YOK_ID_range)
YOK_ID_range

array([154, 147, 101, 136, 112, 130, 165, 198, 166, 135, 180, 144, 107,
       148, 155, 168, 108, 194, 195, 189, 159, 161, 149, 131, 167, 176,
       117, 120, 143, 146, 190, 188, 197, 139, 184, 125, 124, 171, 196,
       138, 122, 150, 126, 153, 142, 191, 100, 104, 170, 185, 121, 199,
       186, 177, 173, 169, 145, 162, 110, 137, 134, 140, 127, 193, 119,
       179, 114, 105, 157, 183, 103, 129, 102, 123, 192, 163, 118, 133,
       172, 132, 160, 115, 151, 164, 156, 182, 116, 141, 181, 187, 128,
       174, 106, 152, 111, 109, 178, 113, 158, 175])

Convert IDs to string values, and append desired prefix:

In [39]:
YOK_ID_strings = [str(ID) for ID in YOK_ID_range]

In [43]:
with_text_YOK_IDs = ["YOK_000000" + ID for ID in YOK_ID_strings]
with_text_YOK_IDs

['YOK_000000154',
 'YOK_000000147',
 'YOK_000000101',
 'YOK_000000136',
 'YOK_000000112',
 'YOK_000000130',
 'YOK_000000165',
 'YOK_000000198',
 'YOK_000000166',
 'YOK_000000135',
 'YOK_000000180',
 'YOK_000000144',
 'YOK_000000107',
 'YOK_000000148',
 'YOK_000000155',
 'YOK_000000168',
 'YOK_000000108',
 'YOK_000000194',
 'YOK_000000195',
 'YOK_000000189',
 'YOK_000000159',
 'YOK_000000161',
 'YOK_000000149',
 'YOK_000000131',
 'YOK_000000167',
 'YOK_000000176',
 'YOK_000000117',
 'YOK_000000120',
 'YOK_000000143',
 'YOK_000000146',
 'YOK_000000190',
 'YOK_000000188',
 'YOK_000000197',
 'YOK_000000139',
 'YOK_000000184',
 'YOK_000000125',
 'YOK_000000124',
 'YOK_000000171',
 'YOK_000000196',
 'YOK_000000138',
 'YOK_000000122',
 'YOK_000000150',
 'YOK_000000126',
 'YOK_000000153',
 'YOK_000000142',
 'YOK_000000191',
 'YOK_000000100',
 'YOK_000000104',
 'YOK_000000170',
 'YOK_000000185',
 'YOK_000000121',
 'YOK_000000199',
 'YOK_000000186',
 'YOK_000000177',
 'YOK_000000173',
 'YOK_0000

In [44]:
PIDN_strings = [str(PIDN) for PIDN in PIDNs]

final_conversion = pd.DataFrame({'Original PIDNs':PIDN_strings,'Yokoyama IDs':with_text_YOK_IDs})


In [45]:
final_conversion

Original PIDNs   Yokoyama IDs
0            3309  YOK_000000154
1            9215  YOK_000000147
2            5143  YOK_000000101
3            8407  YOK_000000136
4            5299  YOK_000000112
..            ...            ...
95           6969  YOK_000000109
96           9482  YOK_000000178
97           7764  YOK_000000113
98           3094  YOK_000000158
99           2064  YOK_000000175

[100 rows x 2 columns]

In [50]:
final_conversion.to_csv(r"/Users/aoddi/Documents/Yokoyama Lab/ADWB/ID Conversion/PIDN_to_YOK_IDS.csv", index=False)