## Procedure for converting PIDNs to Yokoyama Lab IDs

In [1]:
import numpy as np
import pandas as pd
from numpy.random import default_rng

First, import CSV of PIDNs, extract PIDN values:

In [2]:
df = pd.read_csv (r'/Users/aoddi/Documents/Yokoyama Lab/ADWB/ID Conversion/Test PIDNs.csv')
PIDN_col = df.iloc[:,0]
PIDNs = PIDN_col.values
PIDNs

array([3309, 9215, 5143, 8407, 5299, 2056, 3127, 6968, 6369, 6755, 5374,
       3860, 8745, 8417, 8694, 1271, 9940, 2757, 4306, 2479, 4258, 8987,
       5116, 9704, 6747, 7173, 6183, 8914, 3237, 4358, 8664, 7477, 1419,
       3618, 1220, 7709, 9280, 6651, 8428, 5896, 5964, 4499, 2859, 2807,
       7197, 9723, 5753, 4381, 9568, 8275, 9538, 8688, 3119, 8492, 7354,
       5528, 1344, 8114, 4608, 8959, 3346, 1333, 8425, 9669, 1365, 8305,
       6637, 4707, 3022, 8531, 6338, 3977, 5295, 5087, 8620, 2177, 5317,
       5922, 8919, 7009, 2140, 2848, 4649, 5525, 3672, 8347, 3283, 1685,
       9059, 5293, 9240, 1226, 1100, 6263, 5627, 6969, 9482, 7764, 3094,
       2064])

Find number of samples, and select range for new Yokoyama IDs.

In [3]:
num_PIDNs = len(PIDNs)
start = 0
end = start + num_PIDNs
YOK_ID_range = np.arange(start, end)
YOK_ID_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Shuffle array with range of possible IDs.

In [4]:
rng = np.random.default_rng()
rng.shuffle(YOK_ID_range)
YOK_ID_range

array([19, 68, 10,  8,  9, 11, 23, 32, 42, 95, 27, 75, 26,  5, 40, 24, 87,
       39, 20, 76, 54, 66, 55, 98, 69, 71, 91, 49, 31, 17, 45, 53, 83, 18,
       41,  4, 90, 74, 15, 72, 99, 84, 88, 62,  1, 94, 30, 34, 52, 96,  7,
       43, 21, 60,  0, 57, 59,  3, 77, 64, 51, 67, 58, 50, 33, 44, 78,  2,
       97, 36, 89, 86, 22, 28, 82, 25, 48, 38, 12, 93, 65, 47, 13, 61, 14,
       92, 29, 80, 35, 37, 79, 56,  6, 73, 70, 46, 81, 63, 16, 85])

Convert IDs to string values, and append desired prefix:

In [5]:
YOK_ID_strings = [str(ID) for ID in YOK_ID_range]

In [6]:
with_text_YOK_IDs = ["YOK_000000" + ID for ID in YOK_ID_strings]
with_text_YOK_IDs

['YOK_00000019',
 'YOK_00000068',
 'YOK_00000010',
 'YOK_0000008',
 'YOK_0000009',
 'YOK_00000011',
 'YOK_00000023',
 'YOK_00000032',
 'YOK_00000042',
 'YOK_00000095',
 'YOK_00000027',
 'YOK_00000075',
 'YOK_00000026',
 'YOK_0000005',
 'YOK_00000040',
 'YOK_00000024',
 'YOK_00000087',
 'YOK_00000039',
 'YOK_00000020',
 'YOK_00000076',
 'YOK_00000054',
 'YOK_00000066',
 'YOK_00000055',
 'YOK_00000098',
 'YOK_00000069',
 'YOK_00000071',
 'YOK_00000091',
 'YOK_00000049',
 'YOK_00000031',
 'YOK_00000017',
 'YOK_00000045',
 'YOK_00000053',
 'YOK_00000083',
 'YOK_00000018',
 'YOK_00000041',
 'YOK_0000004',
 'YOK_00000090',
 'YOK_00000074',
 'YOK_00000015',
 'YOK_00000072',
 'YOK_00000099',
 'YOK_00000084',
 'YOK_00000088',
 'YOK_00000062',
 'YOK_0000001',
 'YOK_00000094',
 'YOK_00000030',
 'YOK_00000034',
 'YOK_00000052',
 'YOK_00000096',
 'YOK_0000007',
 'YOK_00000043',
 'YOK_00000021',
 'YOK_00000060',
 'YOK_0000000',
 'YOK_00000057',
 'YOK_00000059',
 'YOK_0000003',
 'YOK_00000077',
 'YOK

In [7]:
PIDN_strings = [str(PIDN) for PIDN in PIDNs]

final_conversion = pd.DataFrame({'Original PIDNs':PIDN_strings,'Yokoyama IDs':with_text_YOK_IDs})


In [8]:
final_conversion

Original PIDNs  Yokoyama IDs
0            3309  YOK_00000019
1            9215  YOK_00000068
2            5143  YOK_00000010
3            8407   YOK_0000008
4            5299   YOK_0000009
..            ...           ...
95           6969  YOK_00000046
96           9482  YOK_00000081
97           7764  YOK_00000063
98           3094  YOK_00000016
99           2064  YOK_00000085

[100 rows x 2 columns]

In [9]:
final_conversion.to_csv(r"/Users/aoddi/Documents/Yokoyama Lab/ADWB/ID Conversion/PIDN_to_YOK_IDS.csv", index=False)